export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_PENDING = "GET_PRODUCTS_PENDING";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_PENDING = "GET_PRODUCT_PENDING";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

export const SEARCH_PRODUCTS_SUCCESS = "SEARCH_PRODUCTS_SUCCESS";
export const SEARCH_PRODUCTS_PENDING = "SEARCH_PRODUCTS_PENDING";
export const SEARCH_PRODUCTS_ERROR = "SEARCH_PRODUCTS_ERROR";
